# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Match"
  lane :matchCI do
    create_keychain(
      name: "action_keychain",
      password: "action_keychain_password",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )
    match(
      type: "appstore",
      keychain_name: "action_keychain",
      keychain_password: "action_keychain_password",
      readonly: true
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPLE_KEY_ID"],
      issuer_id: ENV["APPLE_ISSUER_ID"],
      key_content: ENV["APPLE_KEY_CONTENT"]
    )
    build_app(scheme: "GithubActionAppStore")
    upload_to_testflight(api_key: api_key)
  end

  desc "Push a new beta build to TestFlight"
  lane :betaLocal do
    build_app(scheme: "GithubActionAppStore")
    upload_to_testflight()
  end

end
