name: AppStore

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    # Skip when commit/merge message includes "[skip-CD]"
    if: "!contains(github.event.head_commit.message, '[skip-CD]')"

    steps:

    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
    # Set fetch-depth (default: 1) to get whole tree
      with:
        fetch-depth: 0

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
    - name: Bundle install
      run: |
        bundle install

    - name: match Ad-hoc
      run: bundle exec fastlane matchCI
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
      
    - name: Build App and Distibute to Firebase
      run: bundle exec fastlane beta
      env:
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
